# Application Name
spring.application.name=application-service

# Server Port
server.port=8084

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/Application_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=09082003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Optional - Format SQL nicely
spring.jpa.properties.hibernate.format_sql=true

# Eureka (Enable later if you're using Eureka)
# eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

notification.service.url=http://localhost:5007